### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by theGitNoob** [theGitNoob/CS-TCG#13]
- [x] Implement Card Class
- [x] Implement Deck Class
- [x] Implement Field Class
- [x] Implement Game Class
- [x] Make a compiler
- [x] Make the game flow operative
- [x] Implement an artificial player
- [x] Combine the scripting language  
- [x] Format all code
- [x] Implement GameLoop
- [ ] Make a Demo
- [ ] Make the Readme.md
- [ ] Make an UI
